### ISSUE TITLE
ZDF Mediathek ValueError("No JSON object could be decoded")

### ISSUE THREAD

**Issue by Philipp91** [raptor2101/Mediathek#103]
Hi,

I'm getting this error with ZDF. Not sure when it worked for the last time.

```
17:22:06.982 T:196   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "C:\Users\Wohnzimmer\AppData\Roaming\Kodi\addons\plugin.video.mediathek\default.py", line 104, in <module>
                                                mediathek.playVideoFromJsonLink(link);
                                              File "C:\Users\Wohnzimmer\AppData\Roaming\Kodi\addons\plugin.video.mediathek\mediathek\zdf.py", line 132, in playVideoFromJsonLink
                                                jsonObject = json.loads(self.loadPage(link));
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
17:22:07.032 T:1044   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.mediathek/?type=ZDF&action=openJsonLink&link=https%3A%2F%2Fzdf-cdn.live.cellular.de%2FmediathekV2%2Fdocument%2Fheute-show-vom-25-november-2016-102]
```

**Comment by raptor2101** [comment]
is this error still pending?
are all zdf links are broken?
in my mashines zdf works well ...

**Comment by WilliWichtel** [comment]
It's still pending. ZDF works but Arte makes these error.

**Comment by raptor2101** [comment]
can you post a full debug log so i get an idea what is going on?
