### ISSUE TITLE
GetDirectory - Error getting plugin://plugin.video.mediathek/

### ISSUE THREAD

**Issue by white-gecko** [raptor2101/Mediathek#112]
I've tried starting the Mediathek plugin, but I get the following message in the log (`.kodi/temp/kodi.log`):

```
2019-10-27 16:41:28.905 T:1932148320   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-10-27 16:41:29.069 T:1393206144   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named html.entities
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mediathek/default.py", line 20, in <module>
                                                from simplexbmc import SimpleXbmcGui
                                              File "/storage/.kodi/addons/plugin.video.mediathek/simplexbmc.py", line 19, in <module>
                                                from bs4 import BeautifulSoup;
                                              File "/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/__init__.py", line 36, in <module>
                                                from .builder import builder_registry, ParserRejectedMarkup
                                              File "/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/__init__.py", line 7, in <module>
                                                from bs4.element import (
                                              File "/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py", line 13, in <module>
                                                from bs4.dammit import EntitySubstitution
                                              File "/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/dammit.py", line 14, in <module>
                                                from html.entities import codepoint2name
                                            ImportError: No module named html.entities
                                            -->End of Python script error report<--
2019-10-27 16:41:29.091 T:1738830720   ERROR: GetDirectory - Error getting plugin://plugin.video.mediathek/
2019-10-27 16:41:29.093 T:1932148320   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mediathek/) failed
```

**Comment by raptor2101** [comment]
can you give me more log lines, about 10 bevore the error ocure

**Comment by white-gecko** [comment]
Is this really what you are looking for?:

```
2019-10-30 20:35:42.122 T:1790935920  NOTICE: ADDON: script.module.requests v2.22.0 installed
2019-10-30 20:35:42.122 T:1790935920  NOTICE: ADDON: script.module.six v1.11.0 installed
2019-10-30 20:35:42.122 T:1790935920  NOTICE: ADDON: script.module.urllib3 v1.25.3 installed
2019-10-30 20:35:42.122 T:1790935920  NOTICE: ADDON: script.module.xbmcswift2 v2.4.0 installed
2019-10-30 20:35:42.122 T:1790935920  NOTICE: ADDON: script.openweathermap.maps v1.0.0 installed
2019-10-30 20:35:42.122 T:1790935920  NOTICE: ADDON: script.plex v0.1.6 installed
2019-10-30 20:35:42.122 T:1790935920  NOTICE: ADDON: script.program.driverselect v0.1.6 installed
2019-10-30 20:35:42.122 T:1790935920  NOTICE: ADDON: service.libreelec.settings v9.0.0 installed
2019-10-30 20:35:42.122 T:1790935920  NOTICE: ADDON: skin.estuary v2.0.22 installed
2019-10-30 20:35:42.122 T:1790935920  NOTICE: ADDON: vfs.sftp v1.0.1.3 installed
2019-10-30 20:35:42.122 T:1790935920  NOTICE: ADDON: weather.gismeteo v0.3.3 installed
2019-10-30 20:35:42.122 T:1790935920  NOTICE: ADDON: weather.openweathermap.extended v5.0.2 installed
2019-10-30 20:35:42.122 T:1790935920  NOTICE: ADDON: weather.yahoo v5.0.6 installed
2019-10-30 20:35:42.123 T:1790935920  NOTICE: ADDON: webinterface.default v18.x-2.4.6 installed
2019-10-30 20:35:42.123 T:1790935920  NOTICE: ADDON: xbmc.addon v18.2.0 installed
2019-10-30 20:35:42.123 T:1790935920  NOTICE: ADDON: xbmc.core v0.1.0 installed
2019-10-30 20:35:42.123 T:1790935920  NOTICE: ADDON: xbmc.gui v5.14.0 installed
2019-10-30 20:35:42.123 T:1790935920  NOTICE: ADDON: xbmc.json v10.3.0 installed
2019-10-30 20:35:42.123 T:1790935920  NOTICE: ADDON: xbmc.metadata v2.1.0 installed
2019-10-30 20:35:42.123 T:1790935920  NOTICE: ADDON: xbmc.python v2.26.0 installed
2019-10-30 20:35:42.123 T:1790935920  NOTICE: ADDON: xbmc.webinterface v1.0.0 installed
2019-10-30 20:36:04.657 T:1424343920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named html.entities
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mediathek/default.py", line 20, in <module>
                                                from simplexbmc import SimpleXbmcGui
                                              File "/storage/.kodi/addons/plugin.video.mediathek/simplexbmc.py", line 19, in <module>
                                                from bs4 import BeautifulSoup;
                                              File "/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/__init__.py", line 36, in <module>
                                                from .builder import builder_registry, ParserRejectedMarkup
                                              File "/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/__init__.py", line 7, in <module>
                                                from bs4.element import (
                                              File "/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py", line 13, in <module>
                                                from bs4.dammit import EntitySubstitution
                                              File "/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/dammit.py", line 14, in <module>
                                                from html.entities import codepoint2name
                                            ImportError: No module named html.entities
                                            -->End of Python script error report<--
2019-10-30 20:36:04.667 T:1432736624   ERROR: GetDirectory - Error getting plugin://plugin.video.mediathek/?action=openTopicPage&link=http%3a%2f%2fwww.kika.de%2fdie-sendung-mit-der-maus%2fsendereihe454.html&type=KI.KA
2019-10-30 20:36:04.668 T:1936748560   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mediathek/?action=openTopicPage&link=http%3a%2f%2fwww.kika.de%2fdie-sendung-mit-der-maus%2fsendereihe454.html&type=KI.KA) failed
```

Could you tell me maybe more about, what I should look for in the logs?

**Comment by raptor2101** [comment]
this happens during startup?

seems that beautifulsoup4 is unable to load an OS librarie

what OperationSystem you are running kodi on?

**Comment by white-gecko** [comment]
Ah yes, sorry. Yes it is happening right at the start-up. I'm using kodi in Libreelec, it happened on some 9.0 Milhouse, but also on 9.2 libreelec stable.

Am 31. Oktober 2019 19:12:56 MEZ schrieb "Christian Kölpin" <notifications@github.com>:
>this happens during startup?
>
>seems that beautifulsoup4 is unable to load an OS librarie
>
>what OperationSystem you are running kodi on?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/raptor2101/Mediathek/issues/112#issuecomment-548502874

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by raptor2101** [comment]
either your beautifulsoup4 or your python instance ist broken/out of date. html.entities (and codepoint2nam) is a build in pyhton lib.

From the Python Doc "The htmlentitydefs module has been renamed to html.entities in Python 3."

**Comment by white-gecko** [comment]
Now I had the chance to look into this again. I have a libreelec installation on raspberry. It is using a python 2.7.15 …

**Comment by raptor2101** [comment]
Plugin got rejected finaly
