### ISSUE TITLE
3SAT, NDR verpasste Sendung broken

### ISSUE THREAD

**Issue by Matthias84** [raptor2101/Mediathek#84]
Hi,

I noticed, that since 2..3 weeks the plugin crashes, if you try to fetch an item of the "Verpasste Sendungen".
The log looks IMHO like an parser error. Here NDR:

> 20:58:58 T:4964  NOTICE: [Mediathek]: quality: 1
> 20:58:58 T:4964  NOTICE: [Mediathek]: Quality: 1
> 20:58:58 T:4964  NOTICE: [Mediathek]: argv[0]: plugin://plugin.video.mediathek/
> 20:58:58 T:4964  NOTICE: [Mediathek]: argv[1]: 1
> 20:58:58 T:4964  NOTICE: [Mediathek]: download http://www.ndr.de/mediathek/sendungen_a-z/index.html 0
> 20:58:58 T:4964  NOTICE: [Mediathek]: Sendung verpasst?
> 20:58:58 T:4964  NOTICE: [Mediathek]: download http://www.ndr.de/mediathek/sendung_verpasst/epg1490_display-onlyvideo.html 0
> 20:59:03 T:4984  NOTICE: [Mediathek]: quality: 1
> 20:59:03 T:4984  NOTICE: [Mediathek]: Quality: 1
> 20:59:03 T:4984  NOTICE: [Mediathek]: argv[0]: plugin://plugin.video.mediathek/
> 20:59:03 T:4984  NOTICE: [Mediathek]: argv[1]: 2
> 20:59:03 T:4984  NOTICE: [Mediathek]: download http://www.ndr.de/mediathek/sendungen_a-z/index.html 0
> 20:59:03 T:4984  NOTICE: [Mediathek]: http://www.ndr.de/mediathek/sendung_verpasst/epg1490_date-2016-08-13_display-onlyvideo.html
> 20:59:03 T:4984  NOTICE: [Mediathek]: buildPageMenuVerpasst: http://www.ndr.de/mediathek/sendung_verpasst/epg1490_date-2016-08-13_display-onlyvideo.html
> 20:59:03 T:4984  NOTICE: [Mediathek]: download http://www.ndr.de/mediathek/sendung_verpasst/epg1490_date-2016-08-13_display-onlyvideo.html 0
> 20:59:05 T:4984  NOTICE: [Mediathek]: download http://www.ndr.de/mediathek/sendung_verpasst/epg1490_date-2016-08-13_display-onlyvideo.html 1
> 20:59:06 T:4984  NOTICE: [Mediathek]: download http://www.ndr.de/fernsehen/sendungen/die_reportage/Die-Deutschen-aus-Russland-Leben-in-zwei-Welten,diereportage980.html 0
> 20:59:06 T:4984   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "C:\Users\myuser\AppData\Roaming\Kodi\addons\plugin.video.mediathek\default.py", line 76, in <module>
                                                mediathek.buildPageMenu(link, 0);
                                              File "C:\Users\myuser\AppData\Roaming\Kodi\addons\plugin.video.mediathek\mediathek\ndr.py", line 233, in buildPageMenu
                                                self.buildPageMenuVideoListVerpasst(link, initCount)
                                              File "C:\Users\myuser\AppData\Roaming\Kodi\addons\plugin.video.mediathek\mediathek\ndr.py", line 182, in buildPageMenuVideoListVerpasst
                                                self.extractVideoInformation(video_link, None, nodeCount)
                                              File "C:\Users\myuser\AppData\Roaming\Kodi\addons\plugin.video.mediathek\mediathek\ndr.py", line 300, in extractVideoInformation
                                                title = searchResult.group(1).decode('utf-8')
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
> 20:59:06 T:4388   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.mediathek/?action=openTopicPage&link=http%3a%2f%2fwww.ndr.de%2fmediathek%2fsendung_verpasst%2fepg1490_date-2016-08-13_display-onlyvideo.html&type=NDR
> 20:59:06 T:4388   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mediathek/?action=openTopicPage&link=http%3a%2f%2fwww.ndr.de%2fmediathek%2fsendung_verpasst%2fepg1490_date-2016-08-13_display-onlyvideo.html&type=NDR) failed`

And 3SAT:
> 21:02:46 T:4272  NOTICE: [Mediathek]: nano vom 14. Juli 2016
> 21:02:46 T:4272  NOTICE: [Mediathek]: URL:http://nrodl.zdf.de/none/3sat/16/07/160714_sendung_nano_282k_p16v12.webm
> 21:02:46 T:4272  NOTICE: [Mediathek]: Familienpsychologische Gutachten: mangelhaft
> 21:02:46 T:4272  NOTICE: [Mediathek]: URL:http://nrodl.zdf.de/none/3sat/16/07/160706_gutachten_nano_282k_p16v12.webm
> 21:02:46 T:4272   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\myuser\AppData\Roaming\Kodi\addons\plugin.video.mediathek\default.py", line 84, in <module>
                                                mediathek.buildMenu(path)
                                              File "C:\Users\myuser\AppData\Roaming\Kodi\addons\plugin.video.mediathek\mediathek\__init__.py", line 107, in buildMenu
                                                self.buildMenu(path,treeNode);
                                              File "C:\Users\myuser\AppData\Roaming\Kodi\addons\plugin.video.mediathek\mediathek\__init__.py", line 115, in buildMenu
                                                self.buildPageMenu(treeNode.link,len(treeNode.childNodes));
                                              File "C:\Users\myuser\AppData\Roaming\Kodi\addons\plugin.video.mediathek\mediathek\dreisat.py", line 101, in buildPageMenu
                                                self.extractVideoObjects(rssFeed, initCount);
                                              File "C:\Users\myuser\AppData\Roaming\Kodi\addons\plugin.video.mediathek\mediathek\dreisat.py", line 153, in extractVideoObjects
                                                self.extractVideoInformation(itemNode,nodeCount);
                                              File "C:\Users\myuser\AppData\Roaming\Kodi\addons\plugin.video.mediathek\mediathek\dreisat.py", line 170, in extractVideoInformation
                                                pictureNode = itemNode.getElementsByTagName("media:thumbnail")[0];
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
> 21:02:46 T:4388   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.mediathek/?action=openMenu&path=15&type=3Sat
> 21:02:46 T:4388   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mediathek/?action=openMenu&path=15&type=3Sat) failed

This is Windows 7 32bit using Kodi 16.0

**Comment by raptor2101** [comment]
Will look into this ...

**Comment by Matthias84** [comment]
@raptor2101  Thanks for fixing, confirmed to work again :+1:
