### ISSUE TITLE
Some recordings not accessible (due to SSL: CERTIFICATE_VERIFY_FAILED)

### ISSUE THREAD

**Issue by quickstep2** [raptor2101/Mediathek#94]
Some recordings of Arte+7 are not accessible. Reason for this: SSL CERITFICATE_VERIFY_FAILED error on 
read statement sock = urllib2.urlopen( req ) in mediathek\\\_\_init\_\_.py:77
In the error log this error is only reported as "No JSON object could be decoded" (see below).

Quick (and dirty) solution: switch off the verification by replacing the urlopen(...) statement with:
         #quickstep2 start
          #sock = urllib2.urlopen( req )
          import ssl
          gcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1)  # Only for gangstars
          sock = urllib2.urlopen(req, context=gcontext)
          # quickstep2 end

A better solution would be, to inform the user about the certificate problem, offering a dialog with  \<continue>\/\<abort> option.

Problemreport in kodi.log:
07:50:26.337 T:2276   DEBUG: [Mediathek]: download https://api.arte.tv/api/player/v1/config/de/064384-007-A 32
07:50:26.488 T:2276   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "C:\Users\quickstep2\AppData\Roaming\Kodi\addons\plugin.video.mediathek\default.py", line 104, in <module>
                                                mediathek.playVideoFromJsonLink(link);
                                              File "C:\Users\quickstep2\AppData\Roaming\Kodi\addons\plugin.video.mediathek\mediathek\arte.py", line 210, in playVideoFromJsonLink
                                                jsonObject = json.loads(self.loadPage(link));
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--

**Comment by raptor2101** [comment]
should be solved by moving to requests
